### ISSUE TITLE
No module named 'stacked_hourglass.datasets'

### ISSUE THREAD

**Issue by minushuang** [runa91/barc_release#1]
Hi, I have installed the package `pytorch-stacked-hourglas`, and the version is `1.0.0a9`.
but the error `No module named 'stacked_hourglass.datasets'` occurred , when I run the inference script 
`python scripts/test.py --workers 12 --model-file-complete barc_complete/model_best.pth.tar --config barc_cfg_test.yaml`.

btw, It seems that the config params of inference and demo are inverse?

**Comment by runa91** [comment]
should be resolved by now

**Comment by Theo-Cheynel** [comment]
Can confirm that it is resolved with the latest commits

**Comment by minushuang** [comment]
yes, work normally now, thank u very much.
