### ISSUE TITLE
Canonical T-pose mesh?

### ISSUE THREAD

**Issue by Lxiangyue** [runa91/barc_release#11]
Many thanks for your amazing job!

May I ask how to generate the canonical T-pose mesh in Figure 1 in your paper?

**Comment by Lxiangyue** [comment]
I got it!

**Comment by G-Apple1** [comment]
> I got it!

Hello, I also wonder how to  generate the canonical T-pose mesh. Can you teach me？

**Comment by runa91** [comment]
Just set the pose parameters to zeros.

**Comment by G-Apple1** [comment]
> Just set the pose parameters to zeros.

Thank you!
