### ISSUE TITLE
No such file or directory: StanfordExtra_V12/labels/train_stanford_StanfordExtra_v12.npy

### ISSUE THREAD

**Issue by WithFoxSquirrel** [runa91/barc_release#13]
hi, thansk for great works! 
when i trainning model by following commands 
```txt
    python scripts/train.py --workers 12 --checkpoint barc_new_v2 \
    --config barc_cfg_train.yaml \
    start \
    --model-file-hg barc_hg_pret/checkpoint.pth.tar \
    --model-file-3d barc_normflow_pret/checkpoint.pth.tar
```
it failed, error details : 
```txt
FileNotFoundError: [Errno 2] No such file or directory: xx/StanfordExtra_V12/labels/train_stanford_StanfordExtra_v12.npy,
```
if some files are missing, when i download StanfordExtra_V12 datasets, i can't find any train_stanford_StanfordExtra_v12.npy file in directory of StanfordExtra_V12/labels

**Comment by WithFoxSquirrel** [comment]
You must completion annotations are available by filling in the [Google form](https://forms.gle/sRtbicgxsWvRtRmUA). On completion, you will receive an email with the download link.

**Comment by TimenoLong** [comment]
I also meet the same question
