### ISSUE TITLE
wrong tensor size 

### ISSUE THREAD

**Issue by lastbasket** [runa91/barc_release#4]
/barc_release/scripts/../src/combined_model/model_shape_v7.py", line 419, in forward
    pred_pose_rot6d = output['pose'] + pose_rot6d_mean_zeros
RuntimeError: The size of tensor a (35) must match the size of tensor b (12) at non-singleton dimension 1

**Comment by lastbasket** [comment]
The tensor size of these two are torch.Size([4, 35, 6]) torch.Size([1, 12, 6])

**Comment by runa91** [comment]
I can not reproduce that. Did you make any changes to the config files, other than adjusting paths?

**Comment by lastbasket** [comment]
Here are my dataset and checkpoint structure.
![image](https://user-images.githubusercontent.com/55242191/176989224-319b5c26-cd0a-4b13-8d1e-92977c964c26.png)
![image](https://user-images.githubusercontent.com/55242191/176989260-2e78e2e8-957d-4bd7-a91f-d9aebd660712.png)

**Comment by lastbasket** [comment]
I notice that the pose_rot6d_mean_zeros is loaded from statistics_modified_v1.json, could you check the size of this tensor? I think there may be some problems with the loading.

**Comment by runa91** [comment]
If I use the function load_statistics() within data_info.py, i get for pose_rot6d_mean an array of shape (35,6), which is what we want. Is it possible that you changed your version of statistics_modified_v1.json? You may try to download it again.

**Comment by lastbasket** [comment]
I find that it is because I use Dataparallel for 3 gpus training, and the forward() split the size of the tensor from 35->12. I change the training option batch size from 12 to 8 and the training is fine.

**Comment by runa91** [comment]
how does changing the batch size from 12 to 8 help? 35 corresponds to the number of joins...

**Comment by lastbasket** [comment]
Oh, sorry to mention that it is because my single gpu memory is not enough for training of 12 batches. So I try to train on multi-gpus, which leads to this problem.
