### ISSUE TITLE
train.py use too much GPU memory.

### ISSUE THREAD

**Issue by bobby20180331** [runa91/barc_release#5]
RuntimeError: CUDA out of memory. Tried to allocate 192.00 MiB (GPU 0; 31.75 GiB total capacity; 30.38 GiB already allocated; 85.50 MiB free; 30.63 GiB reserved in total by PyTorch)

when I use the training code .32GiB GPU memory is not enough.

**Comment by bobby20180331** [comment]
I change the Batch_size from 48 to 24 in the  training cfg. and the problem above disappeared.
  BATCH_SIZE: 24  #48     # keep 12 (needs to be an even number, as we have a custom data sampler)

**Comment by mshooter** [comment]
how much GPU memory did you have?
