### ISSUE TITLE
barc_hg_pret.pth checkpoint training code share.

### ISSUE THREAD

**Issue by bobby20180331** [runa91/barc_release#6]
@runa91 Thanks a lot for your shares.
Barc result is really realistic, compared with  SOTA method before.  However, the speed seems slower than our expectation.So could  you share the Hourglass training code used for the   barc_hg_pret.pth.tar checkpoint that provide in the code. Thus we can evaluate the hg8/hg2/hg1 performance. Thanks.

**Comment by runa91** [comment]
I was on vacation, but will get back to you soon.
