### ISSUE TITLE
time consuming and low gpu utilization for training the model

### ISSUE THREAD

**Issue by minushuang** [runa91/barc_release#9]
24 batch size for stanford training data, the gpu memory is about 13GB, the gpu utilization is not stable from 0% to 90%, and most of time is 0% waiting for data. does the 3d process resnet, hg8 and model3d entirely compute on gpu?

**Comment by runa91** [comment]
are you using multiple workers for data loading?

**Comment by minushuang** [comment]
I set the workers to 0, I will  set to a bigger number and update this issue

**Comment by runa91** [comment]
data preparation is done on cpu and takes a while. it is highly recommended to use a big number of workers.

**Comment by minushuang** [comment]
i'm sorry for late to update , it doesn't work when i set the works to 24(the machine has 64 processors) , my training image number is about 40,000, and it needs about 90mins for one epoch, which is too slow to optimize the network.
